### ISSUE TITLE
not working as expected

### ISSUE THREAD

**Issue by selaru** [davidgilbertson/easy-ease#1]
i tried using your npm package, but it doesn't steal credit card numbers as advertised on your blog. should i add a trojan on top of it to make it work?

**Comment by davidgilbertson** [comment]
I laughed out loud at this. I feel I have let you down.

You know, anyone reading this in a year's time that's wisely assessing an npm package by reading the issues will wonder what on earth we're going on about.

**Comment by selaru** [comment]
i must admit, i liked your article so much, i had to come here and troll you a bit. feel free to delete this issue or mark it as solved or whatever status you like. i really appreciate your heads up in regards to security issues npm might bring in our pipeline.
thumbs up!

**Comment by davidgilbertson** [comment]
I'm going to respectfully mark this as wontfix :)

**Comment by mariansam** [comment]
I just came across the article and I really started auditing this package if I could maybe notice something suspicious – glad there isn't anything :D

**Comment by davidgilbertson** [comment]
I'm glad you didn't spot it :)
